name: Generate Certificate

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cert
        run: |
          openssl req -x509 -newkey rsa:2048 -keyout mycert.key -out mycert.crt -days 3650 -nodes -subj "/CN=myvpn.local"
      - name: Upload Certificate
        uses: actions/upload-artifact@v4
        with:
          name: my-cert-files
          path: |
            mycert.crt
            mycert.key
